version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      day: "sunday"
      interval: "weekly"
      timezone: "Europe/Berlin"
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      day: "sunday"
      interval: "weekly"
      timezone: "Europe/Berlin"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      day: "sunday"
      interval: "weekly"
      timezone: "Europe/Berlin"
