version: 2
updates:
  # group all dependencies in one PR
  - package-ecosystem: "cargo"
    allow:
      - dependency-type: "all"
    directory: "/"
    groups:
      rust-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 1
    schedule:
      day: "friday"
      interval: "monthly"
      timezone: "Europe/Berlin"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      day: "friday"
      interval: "monthly"
      timezone: "Europe/Berlin"
