name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

env:
  # Will be overwritten by Act (https://nektosact.com/).
  ACT: false
  # Will be computed later.
  ARCHIVE_PATH: ''
  # Will be overwritten when run locally.
  ARTIFACT_DIR: '.'
  # Name of the artifact to produce.
  ARTIFACT_NAME: java-updater

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        # skip step when run locally with act
        if: ${{ !env.ACT }}
        run: gh release create ${{ github.ref_name }}
  assets:
    needs: release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - apt: 'gcc-aarch64-linux-gnu'
            archive: .tar.gz
            build: linux-arm
            linker: aarch64-linux-gnu-gcc
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - apt: 'gcc-i686-linux-gnu'
            archive: .tar.gz
            build: linux-32-bit
            linker: i686-linux-gnu-gcc
            os: ubuntu-latest
            target: i686-unknown-linux-gnu
          - apt: 'gcc-x86-64-linux-gnu'
            archive: .tar.gz
            build: linux-64-bit
            linker: x86_64-linux-gnu-gcc
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - archive: .zip
            build: windows-arm
            ext: .exe
            os: windows-latest
            target: aarch64-pc-windows-msvc
          - archive: .zip
            build: windows-32-bit
            ext: .exe
            os: windows-latest
            target: i686-pc-windows-msvc
          - archive: .zip
            build: windows-64-bit
            ext: .exe
            os: windows-latest
            target: x86_64-pc-windows-msvc
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          targets: ${{ matrix.target }}
          toolchain: '1.90.0'
      - name: Install cross compiler
        if: matrix.apt != ''
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.apt }}
      - name: Configure linker
        if: matrix.linker != ''
        run: |
          mkdir -p ~/.cargo
          cat >> ~/.cargo/config.toml <<EOF
          [target.${{ matrix.target }}]
          linker = "${{ matrix.linker }}"
          EOF
      - name: Install cargo-auditable
        uses: taiki-e/cache-cargo-install-action@v3
        with:
          tool: cargo-auditable
      - name: Build
        # env:
        #   RUSTFLAGS: -Zon-broken-pipe=kill
        run: cargo auditable build --locked --release --target ${{ matrix.target }}
      # 7z is available on all runners.
      # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#preinstalled-software
      - name: Create tar.gz archive
        id: archive-tar-gz
        if: matrix.archive == '.tar.gz'
        shell: bash
        run: |
          DIRECTORY="${{ env.ARTIFACT_DIR }}/${{ env.ARTIFACT_NAME }}-${{ github.ref_name }}-${{ matrix.build }}"
          mkdir -p "${DIRECTORY}"
          cp license* "target/${{ matrix.target }}/release/${{ env.ARTIFACT_NAME }}${{ matrix.ext }}" "${DIRECTORY}"
          tar -zcvf "${DIRECTORY}${{ matrix.archive }}" "${DIRECTORY}"
          echo "ARCHIVE_PATH=${DIRECTORY}${{ matrix.archive }}" >> ${GITHUB_ENV}
      - name: Create zip archive
        id: archive-zip
        if: matrix.archive == '.zip'
        shell: bash
        run: |
          DIRECTORY="${{ env.ARTIFACT_DIR }}${{ env.ARTIFACT_NAME }}-${{ github.ref_name }}-${{ matrix.build }}"
          mkdir -p "${DIRECTORY}"
          cp license* "target/${{ matrix.target }}/release/${{ env.ARTIFACT_NAME }}${{ matrix.ext }}" "${DIRECTORY}"
          7z a "${DIRECTORY}${{ matrix.archive }}" "${DIRECTORY}"
          echo "ARCHIVE_PATH=${DIRECTORY}/${{ matrix.archive }}" >> ${GITHUB_ENV}
      - name: Show some env variables
        run: |
          echo "ACT => ${{ env.ACT }}"
          echo "ARCHIVE_PATH => ${{ env.ARCHIVE_PATH }}"
      - name: Upload release artifacts
        env:
          GH_TOKEN: ${{ github.token }}
        # skip step when run locally with act
        if: ${{ !env.ACT && env.ARCHIVE_PATH != ''}}
        run: gh release upload ${{ github.ref_name }} ${{ env.ARCHIVE_PATH }}

permissions:
  contents: write
